# Generated by Django 4.0.4 on 2022-04-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='note',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='comments.note'),
            preserve_default=False,
        ),
    ]
