# Generated by Django 4.0.4 on 2022-04-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_comment_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='note',
            new_name='parent_note',
        ),
    ]
