# Generated by Django 4.0.4 on 2022-04-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_rename_note_comment_parent_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_note',
            new_name='note',
        ),
    ]
