# Generated by Django 4.0.4 on 2022-04-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_rename_parent_note_comment_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
    ]
